DROP TABLE IF EXISTS `deployment`;
DROP TABLE IF EXISTS `environment_codebase_pair`;
DROP TABLE IF EXISTS `environment`;
DROP TABLE IF EXISTS `vpn`;
DROP TABLE IF EXISTS `codebase`;

CREATE TABLE `codebase` (
    CODEBASE_ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(512) NOT NULL,
    URL VARCHAR(2000) NOT NULL,
    URL_SHA2 CHAR(64) NOT NULL,
    PROJECT_CODE VARCHAR(15) NOT NULL,
    PRIMARY KEY (`CODEBASE_ID`),
    UNIQUE(URL_SHA2),
    UNIQUE(PROJECT_CODE)
);

CREATE TABLE `vpn` (
    VPN_ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(512) NOT NULL,
    URL VARCHAR(2000) NOT NULL,
    URL_SHA2 CHAR(64) NOT NULL,
    ORGANIZATION VARCHAR(512) NOT NULL,
    PRIMARY KEY (`VPN_ID`),
    UNIQUE(URL_SHA2)
);

CREATE TABLE `environment` (
    ENVIRONMENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(512) NOT NULL,
    DOMAIN VARCHAR(512) NOT NULL,
    VPN_ID INT(11) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL DEFAULT '',
    EXTRA_FIELDS JSON NOT NULL,
    PRIMARY KEY (`ENVIRONMENT_ID`),
    FOREIGN KEY (`VPN_ID`) REFERENCES `vpn` (`VPN_ID`),
    UNIQUE(NAME)
);

CREATE TABLE `environment_codebase_pair` (
    ENVIRONMENT_CODEBASE_PAIR_ID INT(11) NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INT(11) NOT NULL,
    CODEBASE_ID INT(11) NOT NULL,
    PRIMARY KEY (`ENVIRONMENT_CODEBASE_PAIR_ID`),
    FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `environment` (`ENVIRONMENT_ID`),
    FOREIGN KEY (`CODEBASE_ID`) REFERENCES `codebase` (`CODEBASE_ID`),
    UNIQUE(ENVIRONMENT_ID, CODEBASE_ID)
);

CREATE TABLE `deployment` (
    DEPLOYMENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INT(11) NOT NULL,
    DEPLOYMENT_DATE DATETIME NOT NULL,
    PREVIOUS_DEPLOYMENT_ID INT(11),
    PRIMARY KEY (`DEPLOYMENT_ID`),
    FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `environment` (`ENVIRONMENT_ID`),
    FOREIGN KEY (`PREVIOUS_DEPLOYMENT_ID`) REFERENCES `deployment` (`DEPLOYMENT_ID`) ON DELETE SET NULL
);

INSERT INTO `vpn` (VPN_ID, NAME, URL, URL_SHA2, ORGANIZATION) VALUES
    (1, 'MY cool VPN', 'foo.com', SHA2('foo.com', 256), 'Me'),
    (2, 'MY cool VPN 2', 'foo2.com', SHA2('foo2.com', 256), 'Me');

INSERT INTO `codebase` (CODEBASE_ID, NAME, URL, URL_SHA2, PROJECT_CODE) VALUES
    (1, 'PIC-SURE', 'https://github.com/hms-dbmi/pic-sure', SHA2('https://github.com/hms-dbmi/pic-sure', 256), 'IDK'),
    (2, 'HPDS', 'https://github.com/hms-dbmi/pic-sure-hpds', SHA2('https://github.com/hms-dbmi/pic-sure-hpds', 256), 'WOO');

INSERT INTO `environment` (ENVIRONMENT_ID, NAME, DOMAIN, VPN_ID, DESCRIPTION, EXTRA_FIELDS) VALUES
    (1, 'GIC BCH Dev', 'gic-bch-dev.pl.hms.harvard.edu', 1, 'Boston Children\'s GIC Institute node (dev)', '{}'),
    (2, 'GIC Common Area DEv', 'gic.hms.harvard.edu', 1, 'GIC Common Area', '{}');

INSERT INTO `environment_codebase_pair` (ENVIRONMENT_CODEBASE_PAIR_ID, ENVIRONMENT_ID, CODEBASE_ID) VALUES
    (1, 1, 1),
    (2, 1, 2);

INSERT INTO `deployment` (DEPLOYMENT_ID, ENVIRONMENT_ID, DEPLOYMENT_DATE, PREVIOUS_DEPLOYMENT_ID) VALUES
    (1, 1, '2022-01-01 00:00:00', NULL),
    (2, 1, '2022-01-02 00:00:00', 1);